import * as React from "react";
import { Text } from "react-native";
import DarkContainer from "../darkContainer";
import LightContainer from "../lightContainer";

export default function Scoreboard() {
  return (
    <>
      <DarkContainer text="Poängliga"></DarkContainer>
      <LightContainer>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
        <Text>BAJS</Text>
      </LightContainer>
    </>
  );
}
